[package]
name = "chroma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-once-cell = "0.5.3"
logos = "0.13.0"
tokio = "1.35.1"
